name: yms
description: YMS - mini couple PWA
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  
  # Firebase
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_messaging: ^16.1.1
  firebase_auth: ^6.1.4

  # Storage
  shared_preferences: ^2.2.3

  # UI / QR
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0

  # Location
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true